### PR TITLE
compile with trunk

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
This patch is needed to compile trunk, which is needed to test flambda+trunk

**Comment by diml** [comment]
Thanks, we can't merge this yet as it will break compatibility with the current released compiler. 
At some point I'm planning to setup branches that follow trunk in all our packages with maybe a dedicated opam repository, but it's not ready yet  on our side.

**Comment by samoht** [comment]
I've rebased my patch to current trunk.

**Comment by samoht** [comment]
The patch seems to be in, so closing :-)

**Pull request closed without merging**
